### ISSUE TITLE
Firmware update fails due to NZXT CAM Software

### ISSUE THREAD

**Issue by GazHank** [Dygmalab/Bazecor#189]
**Describe the bug**
Unable to upgrade to firmware 0.3.0 from 0.2.7.

**To Reproduce**
1. Connect keyboard
2. select update firmware
3. choose to update
4. press escape key when prompted
5. neuron goes into a blue fit
6. errors are recored in the console (see screenshot below)
7. keyboard doesn't update, and is unresponsive unless the neuron is unplugged and reconneded, at which point everything is back to normal (without the update)

**Expected behavior**
well I guess the firmware should be updated

**Screenshots**
Port not open error:
![image](https://user-images.githubusercontent.com/64541249/113233246-b38c5400-9296-11eb-8837-b5d4414e5c24.png)

**Desktop (please complete the following information):**
 - OS: win10 (build 19042)
 - Bazecor Version: [ 0.3.0]

**Additional context**
I'll try to use an earlier version of the bazecor software to update the firmware

**Comment by AlexDygma** [comment]
I have seen this a couple times, but it always works again after closing the proceses that could be using the COM port at the same time.

it seems sometimes the serial ports are in use because of a process that wasn't closed properly ( for example Bazecor sometimes seems to close poorly and hijacks the port for a longer time than it should.

if it's happening to you every time that you start the application, try to restart your computer to see if a weird process is remaining active on the background.

**Comment by GazHank** [comment]
Thanks @AlexDygma,

It looks like the first error message ("port is not open") is due to trying to close a connection that isn't open.  It's been fixed in Chrysalis so we just need to adopt their change: https://github.com/keyboardio/Chrysalis/commit/642fd3cef811843f87093b996f9f8eb5a96de5d4#diff-27a98ee25d928b3b2473db0e71ff7a81abd74f1772aa29d53e0ca2a15922d4f5

The second error message is due to us trying to reconnect to the keyboard while it is Firmware update mode, I would like to trap that error and handle it more ellegantly, but for now I'm going to try tracing the error back a few steps, as both these error messages happen after the actual FW update issue.

I've tried reboots, and loading the 0.3.0 hex file using other versions of the application (0.2.5, 0.2.6, 0.2.7 and 0.3.0)  all having the same impact.  I'm currently running the pre-release version of the firmware, so I might need to try resetting back to factory default or an earlier version and then upgrading.

**Comment by GazHank** [comment]
@AlexDygma, it looks like the issue is a conflict with the NZXT CAM software that controls my cooler.  I'll raise it with them, and seem if we can trap this error more elegantly when it does occur.

**Comment by GazHank** [comment]
I've updated the title of this issue to make it more discoverable for others who experience the same problem.  The quick workaround for now is to quit the NZXT CAM software before updating the firmware, and then restart it afterwards.

**Comment by AlexDygma** [comment]
Hey @GazHank !

Im glad you discovered your root cause for this problem!  

> It looks like the first error message ("port is not open") is due to trying to close a connection that isn't open. It's been fixed in Chrysalis so we just need to adopt their change: [keyboardio@642fd3c#diff-27a98ee25d928b3b2473db0e71ff7a81abd74f1772aa29d53e0ca2a15922d4f5](https://github.com/keyboardio/Chrysalis/commit/642fd3cef811843f87093b996f9f8eb5a96de5d4#diff-27a98ee25d928b3b2473db0e71ff7a81abd74f1772aa29d53e0ca2a15922d4f5)

I just added a PR that i will merge to solve this point after looking at the fix from chrysalis.

> @AlexDygma, it looks like the issue is a conflict with the NZXT CAM software that controls my cooler. I'll raise it with them, and seem if we can trap this error more elegantly when it does occur.

At least we know the source of the problem, it would be nice to know exactly why they are considering the serial port as a device valid for them to connect to...

it's strange..

**Comment by GazHank** [comment]
Hey @AlexDygma,

Thanks for pulling that change through.  Although having tried that code change it only stops us from thowing an error after the issue has occured.  It would be nice to trace this back and more elegantly handle the fact that CAM has stolen our USB connection.

> At least we know the source of the problem, it would be nice to know exactly why they are considering the serial port as a device valid for them to connect to...

The CAM software is also Electron based, and the AIO pump and fans are controlled over a USB connection, so I expect they are either using some old (buggy) version off the usb packages we are using, or more likely I suspect they may be incorrectly contacting or polling devices that they shouldn't care about.

I plan to try to trace the error so that we can handle them properly, by notifying the user of the issue (rather that just hanging on the update screen).  However I think I need to focus on getting the package updates and theming fixes ready (they are pretty close :-)

Cheers

Gareth

**Comment by AlexDygma** [comment]
Sounds Great! 😄

**Comment by AlexDygma** [comment]
Will keep this opened until you get notice from NZXT!

**Comment by GazHank** [comment]
@AlexDygma are you able to share any extra info about the changes for the timeouts in resetKeyboard within the flashing process?  I particular the changes that were introduced for Mac/Darwin?  https://github.com/Dygmalab/Bazecor/commit/9f84c9f8b0c747f97f09353ef6c96098968d275a

It appears that setting the bootLoaderUp to the Mac value of 4250 allows the firmware process to work both with or without CAM running.  It's not perfect as there are still some errors getting thrown, but I wonder if other activity on the USB stack is simply slowing the device entering bootloader state or something like that?

**Comment by AlexDygma** [comment]
Hey @GazHank !

I have done several heavy modifications to the connection process, so it should no longer fail in any circumstances, please check if the problem is now solved!

if it is we will close this issue

**Comment by GazHank** [comment]
Hey @AlexDygma,

the firmware update process seems to get a little further, but it still doesnt complete.  I'd send a follow up e-mail to Nzxt yesterday as they suggested fix (fully removing and reinstalling the software) didnt work.

Previously the Keyboard would enter bootloader mode, but the fast flickering of the neuron either wouldnt happen, or would be very short.  Now the flashing does seem to last a little longer, but it still doesnt complete.  The keyboard is then left in bootloader mode (slow pulsing blue neuron), and the software is stuck at the firmware update screen.  The only course of action is to kill the app, and unplug the keyboard (to get it back to normal mode).

At the moment I'm considering this to be a two sided issue.  Nzxt CAM not playing nice with other hardware, and our bootloader/firmware process not being fault tollerant.

Weirdly it doesnt look like the keybaord is throwing errors during the failed firmware process, so I still think it might just be down to timeouts or something like that.  However it's interesting that when the keyboard is in it's normal mode, the CAM software (upon initialisation), sends a number of Get Description requests which result in the keyboard replying with malformed messages (only the replies appear to be malformed)....

I should be back on my desktop machine this evening if you would like me to share any logs, or further info on the issue.

**Comment by GazHank** [comment]
Wow @AlexDygma, some real process with 0.3.3 - the firmware update itself now works, however the settings for the keyboard are not fully reinstated, and the software is left in limbo (stuck on the firmware update screen).

Specifically:
- the firmware version is updated (checked by comparing the examining the firmware version in the firmware update screen).
- Keyboard settings are not reinstated, specifically the colour palette as all of the colours are set to black.

I've pasted some of the error messages from the dev console in case that helps with the diagnostics.  Let me know if any other info would be helpful

upon commencement of the firmware update:
![image](https://user-images.githubusercontent.com/64541249/115382057-2456ca00-a1cc-11eb-8de2-0a70be1f449d.png)
upon completion of the update:
![image](https://user-images.githubusercontent.com/64541249/115382127-3b95b780-a1cc-11eb-84da-e8cb99f6ef8c.png)

**Comment by AlexDygma** [comment]
This happens every time you flash with the NZXT app? maybe when the keyboard is rebooting after a successful flash, it's captured by the NZXT app before Bazecor, as it now has more delay to wait for it.

**Comment by GazHank** [comment]
@AlexDygma yes that's right.  It's actually caused me to look into some of the open source alternatives, it actually looks like https://github.com/liquidctl/liquidctl might be a suitable alternative, and removes the need for an electron app to be sitting in the background interfering with my USB devices :-D

**Comment by AlexDygma** [comment]
Glad you found an alternative!

Just baffled at how they made an app that doesn't even check the vendor & device tags to know if it's theirs or not...
